
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author waniya_mustafa
 */
public class adminMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form adminMainMenu
     */
    public adminMainMenu() {
        initComponents();
         ImageIcon background_img= new ImageIcon("/Users/waniya_mustafa/NetBeansProjects/DBMS_Project/src/DBMS-ProjectImages/adminMainMenu.jpg","");
          Image  img= background_img.getImage();
          Image temp_img=img.getScaledInstance(1200, 700,Image.SCALE_SMOOTH);
           background_img=new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
                     backgrnd.setBounds(0, 0, 1200,700);
                     this.add(backgrnd);
                     bankLogBtn.setOpaque(true);
                     userInfoBtn.setOpaque(true);
                     createUserBtn.setOpaque(true);
                     deleteUserBtn.setOpaque(true);
                     transactionHistoryBtn.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteUserBtn = new javax.swing.JButton();
        userInfoBtn = new javax.swing.JButton();
        createUserBtn = new javax.swing.JButton();
        bankLogBtn = new javax.swing.JButton();
        transactionHistoryBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Menu");

        deleteUserBtn.setBackground(new java.awt.Color(129, 228, 218));
        deleteUserBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        deleteUserBtn.setForeground(new java.awt.Color(0, 0, 0));
        deleteUserBtn.setText("Delete User");
        deleteUserBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        deleteUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtnActionPerformed(evt);
            }
        });

        userInfoBtn.setBackground(new java.awt.Color(129, 228, 218));
        userInfoBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        userInfoBtn.setForeground(new java.awt.Color(0, 0, 0));
        userInfoBtn.setText("User Information");
        userInfoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        userInfoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInfoBtnActionPerformed(evt);
            }
        });

        createUserBtn.setBackground(new java.awt.Color(129, 228, 218));
        createUserBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        createUserBtn.setForeground(new java.awt.Color(0, 0, 0));
        createUserBtn.setText("Create User");
        createUserBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        createUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        bankLogBtn.setBackground(new java.awt.Color(129, 228, 218));
        bankLogBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        bankLogBtn.setForeground(new java.awt.Color(0, 0, 0));
        bankLogBtn.setText("Bank Log");
        bankLogBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        bankLogBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        transactionHistoryBtn.setBackground(new java.awt.Color(129, 228, 218));
        transactionHistoryBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        transactionHistoryBtn.setForeground(new java.awt.Color(0, 0, 0));
        transactionHistoryBtn.setText("View Transaction History");
        transactionHistoryBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        transactionHistoryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(865, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(deleteUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(transactionHistoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(bankLogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(105, 105, 105)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(createUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(deleteUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(userInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(bankLogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(transactionHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUserBtnActionPerformed

    private void userInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInfoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInfoBtnActionPerformed

    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createUserBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bankLogBtn;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JButton deleteUserBtn;
    private javax.swing.JButton transactionHistoryBtn;
    private javax.swing.JButton userInfoBtn;
    // End of variables declaration//GEN-END:variables
}
