
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author waniya_mustafa
 */
public class MainMenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame() {
        initComponents();
           ImageIcon background_img= new ImageIcon("/Users/waniya_mustafa/NetBeansProjects/DBMS_Project/src/DBMS-ProjectImages/userMainMenu.jpg","");
          Image  img= background_img.getImage();
          Image temp_img=img.getScaledInstance(1200, 700,Image.SCALE_SMOOTH);
           background_img=new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
                     backgrnd.setBounds(0, 0, 1200,700);
                     this.add(backgrnd);
                     changePssBtn.setOpaque(true);
                     cashDepositBtn.setOpaque(true);
                     cashWithdrawlBtn.setOpaque(true);
                     balanceInquiryBtn.setOpaque(true);
                     historyBtn.setOpaque(true);
                     transferMoneyBtn.setOpaque(true);
                     closeAcctBtn.setOpaque(true);
                     changePssBtn.setOpaque(true);
                      logOutBtn.setOpaque(true);
                     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashDepositBtn = new javax.swing.JButton();
        cashWithdrawlBtn = new javax.swing.JButton();
        changePssBtn = new javax.swing.JButton();
        transferMoneyBtn = new javax.swing.JButton();
        balanceInquiryBtn = new javax.swing.JButton();
        closeAcctBtn = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cashDepositBtn.setBackground(new java.awt.Color(129, 228, 218));
        cashDepositBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        cashDepositBtn.setForeground(new java.awt.Color(0, 0, 0));
        cashDepositBtn.setText("Cash Deposit");
        cashDepositBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        cashDepositBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cashWithdrawlBtn.setBackground(new java.awt.Color(129, 228, 218));
        cashWithdrawlBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        cashWithdrawlBtn.setForeground(new java.awt.Color(0, 0, 0));
        cashWithdrawlBtn.setText("Cash Withdrawl");
        cashWithdrawlBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        cashWithdrawlBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cashWithdrawlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashWithdrawlBtnActionPerformed(evt);
            }
        });

        changePssBtn.setBackground(new java.awt.Color(129, 228, 218));
        changePssBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        changePssBtn.setForeground(new java.awt.Color(0, 0, 0));
        changePssBtn.setText("Change Password");
        changePssBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        changePssBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        transferMoneyBtn.setBackground(new java.awt.Color(129, 228, 218));
        transferMoneyBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        transferMoneyBtn.setForeground(new java.awt.Color(0, 0, 0));
        transferMoneyBtn.setText("Transfer Money");
        transferMoneyBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        transferMoneyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        balanceInquiryBtn.setBackground(new java.awt.Color(129, 228, 218));
        balanceInquiryBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        balanceInquiryBtn.setForeground(new java.awt.Color(0, 0, 0));
        balanceInquiryBtn.setText("Balance Inquiry");
        balanceInquiryBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        balanceInquiryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balanceInquiryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceInquiryBtnActionPerformed(evt);
            }
        });

        closeAcctBtn.setBackground(new java.awt.Color(129, 228, 218));
        closeAcctBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        closeAcctBtn.setForeground(new java.awt.Color(0, 0, 0));
        closeAcctBtn.setText("Account Closure");
        closeAcctBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        closeAcctBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        historyBtn.setBackground(new java.awt.Color(129, 228, 218));
        historyBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        historyBtn.setForeground(new java.awt.Color(0, 0, 0));
        historyBtn.setText("Transaction History");
        historyBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        historyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(129, 228, 218));
        logOutBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(0, 0, 0));
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        logOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cashWithdrawlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(188, 188, 188)
                            .addComponent(cashDepositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(balanceInquiryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(188, 188, 188)
                                .addComponent(transferMoneyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(188, 188, 188)
                                .addComponent(closeAcctBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changePssBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(368, 368, 368)))
                .addContainerGap(492, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(529, Short.MAX_VALUE)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(491, 491, 491)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashWithdrawlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashDepositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceInquiryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferMoneyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeAcctBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(changePssBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(485, Short.MAX_VALUE)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(165, 165, 165)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashWithdrawlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashWithdrawlBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashWithdrawlBtnActionPerformed

    private void balanceInquiryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceInquiryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceInquiryBtnActionPerformed

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyBtnActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balanceInquiryBtn;
    private javax.swing.JButton cashDepositBtn;
    private javax.swing.JButton cashWithdrawlBtn;
    private javax.swing.JButton changePssBtn;
    private javax.swing.JButton closeAcctBtn;
    private javax.swing.JButton historyBtn;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton transferMoneyBtn;
    // End of variables declaration//GEN-END:variables
}
