
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author waniya_mustafa
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
                  //Adding Image to the Label for Background
        ImageIcon background_img= new ImageIcon("/Users/waniya_mustafa/NetBeansProjects/DBMS_Project/src/DBMS-ProjectImages/mainFrame.jpeg","");
          Image  img= background_img.getImage();
          Image temp_img=img.getScaledInstance(1200, 700,Image.SCALE_SMOOTH);
           background_img=new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
                     backgrnd.setBounds(0, 0, 1199,722);
                     this.add(backgrnd);
                     SignUpBtn.setOpaque(true);
                     userLoginBtn.setOpaque(true);
                     adminLoginBtn.setOpaque(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        adminLoginBtn = new javax.swing.JButton();
        userLoginBtn = new javax.swing.JButton();
        SignUpBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mainFrame");

        adminLoginBtn.setBackground(new java.awt.Color(129, 228, 218));
        adminLoginBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        adminLoginBtn.setForeground(new java.awt.Color(0, 0, 0));
        adminLoginBtn.setText("Admin Login");
        adminLoginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        adminLoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        userLoginBtn.setBackground(new java.awt.Color(129, 228, 218));
        userLoginBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        userLoginBtn.setForeground(new java.awt.Color(0, 0, 0));
        userLoginBtn.setText("User Login");
        userLoginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        userLoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        SignUpBtn.setBackground(new java.awt.Color(129, 228, 218));
        SignUpBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        SignUpBtn.setForeground(new java.awt.Color(0, 0, 0));
        SignUpBtn.setText("Sign Up");
        SignUpBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        SignUpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(userLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(adminLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(332, 332, 332))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(490, 490, 490))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153)
                .addComponent(SignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignUpBtn;
    private javax.swing.JButton adminLoginBtn;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton userLoginBtn;
    // End of variables declaration//GEN-END:variables
}
