
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author waniya_mustafa
 */
public class transferMoneyFrame extends javax.swing.JFrame {

    /**
     * Creates new form transferMoneyFrame
     */
    public transferMoneyFrame() {
        initComponents();
           ImageIcon background_img= new ImageIcon("/Users/waniya_mustafa/NetBeansProjects/DBMS_Project/src/DBMS-ProjectImages/TransferMoney.jpg","");
          Image  img= background_img.getImage();
          Image temp_img=img.getScaledInstance(950, 695,Image.SCALE_SMOOTH);
           background_img=new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
                     backgrnd.setBounds(0, 0,950,695);
                     this.add(backgrnd);
                     transferMoneyBtn.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        receiverAcct = new javax.swing.JTextField();
        transferPss = new javax.swing.JPasswordField();
        transferMoneyBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        transferAmount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("To Account");

        jLabel2.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Transaction Password");

        receiverAcct.setBackground(new java.awt.Color(204, 204, 204));
        receiverAcct.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        receiverAcct.setForeground(new java.awt.Color(0, 0, 0));
        receiverAcct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        receiverAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverAcctActionPerformed(evt);
            }
        });

        transferPss.setBackground(new java.awt.Color(204, 204, 204));
        transferPss.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        transferPss.setForeground(new java.awt.Color(0, 0, 0));
        transferPss.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        transferPss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferPssActionPerformed(evt);
            }
        });

        transferMoneyBtn.setBackground(new java.awt.Color(0, 153, 153));
        transferMoneyBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        transferMoneyBtn.setForeground(new java.awt.Color(255, 255, 255));
        transferMoneyBtn.setText("Transfer");
        transferMoneyBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 3, true));
        transferMoneyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transferMoneyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferMoneyBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Amount");

        transferAmount.setBackground(new java.awt.Color(204, 204, 204));
        transferAmount.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        transferAmount.setForeground(new java.awt.Color(0, 0, 0));
        transferAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        transferAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferAmountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(617, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(receiverAcct)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferPss, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(transferMoneyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(receiverAcct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(transferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transferPss, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(transferMoneyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receiverAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverAcctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverAcctActionPerformed

    private void transferPssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferPssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferPssActionPerformed

    private void transferMoneyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferMoneyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferMoneyBtnActionPerformed

    private void transferAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferAmountActionPerformed

    /**
     * @param args the command line arguments
     */
 
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField receiverAcct;
    private javax.swing.JTextField transferAmount;
    private javax.swing.JButton transferMoneyBtn;
    private javax.swing.JPasswordField transferPss;
    private javax.swing.JTextField userNameField;
    private javax.swing.JTextField userNameField1;
    // End of variables declaration//GEN-END:variables
}
