
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author waniya_mustafa
 */
public class userSignUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form userSignUpFrame
     */
    public userSignUpFrame() {
        initComponents();
        
              ImageIcon background_img= new ImageIcon("/Users/waniya_mustafa/NetBeansProjects/DBMS_Project/src/DBMS-ProjectImages/userSignUp.jpg","");
          Image  img= background_img.getImage();
          Image temp_img=img.getScaledInstance(749, 859,Image.SCALE_SMOOTH);
           background_img=new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
                     backgrnd.setBounds(0, 0, 749,859);
                     this.add(backgrnd);
                     SignUpBtn.setOpaque(true);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPassword = new javax.swing.JPasswordField();
        SignUpBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userContactNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        userCity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        savingAcctCB = new javax.swing.JCheckBox();
        CurrentAcctCB = new javax.swing.JCheckBox();
        userDeposit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        userEmailAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");

        userPassword.setBackground(new java.awt.Color(204, 204, 204));
        userPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        userPassword.setForeground(new java.awt.Color(0, 0, 0));
        userPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        userPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPasswordActionPerformed(evt);
            }
        });

        SignUpBtn.setBackground(new java.awt.Color(153, 0, 153));
        SignUpBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        SignUpBtn.setForeground(new java.awt.Color(255, 255, 255));
        SignUpBtn.setText("Sign Up");
        SignUpBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 3, true));
        SignUpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Password");

        userFirstName.setBackground(new java.awt.Color(204, 204, 204));
        userFirstName.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        userFirstName.setForeground(new java.awt.Color(0, 0, 0));
        userFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        userFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFirstNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Contact Number");

        userLastName.setBackground(new java.awt.Color(204, 204, 204));
        userLastName.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        userLastName.setForeground(new java.awt.Color(0, 0, 0));
        userLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        userLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLastNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Last Name");

        userContactNumber.setBackground(new java.awt.Color(204, 204, 204));
        userContactNumber.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        userContactNumber.setForeground(new java.awt.Color(0, 0, 0));
        userContactNumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        userContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userContactNumberActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("City");

        userCity.setBackground(new java.awt.Color(204, 204, 204));
        userCity.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        userCity.setForeground(new java.awt.Color(0, 0, 0));
        userCity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        userCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCityActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Account Type");

        savingAcctCB.setText("Savings Account");
        savingAcctCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingAcctCBActionPerformed(evt);
            }
        });

        CurrentAcctCB.setText("Current Account");
        CurrentAcctCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentAcctCBActionPerformed(evt);
            }
        });

        userDeposit.setBackground(new java.awt.Color(204, 204, 204));
        userDeposit.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        userDeposit.setForeground(new java.awt.Color(0, 0, 0));
        userDeposit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        userDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDepositActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Initial Deposit");

        userEmailAddress.setBackground(new java.awt.Color(204, 204, 204));
        userEmailAddress.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        userEmailAddress.setForeground(new java.awt.Color(0, 0, 0));
        userEmailAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        userEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailAddressActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Email Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userFirstName)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userPassword)
                                .addComponent(userCity)
                                .addComponent(userContactNumber)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(savingAcctCB, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CurrentAcctCB, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(userDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(SignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savingAcctCB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentAcctCB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(userDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(userEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(SignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordActionPerformed

    private void SignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpBtnActionPerformed

    private void userFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFirstNameActionPerformed

    private void userLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLastNameActionPerformed

    private void userContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userContactNumberActionPerformed

    private void userCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userCityActionPerformed

    private void savingAcctCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingAcctCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingAcctCBActionPerformed

    private void CurrentAcctCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentAcctCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentAcctCBActionPerformed

    private void userDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userDepositActionPerformed

    private void userEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEmailAddressActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CurrentAcctCB;
    private javax.swing.JButton SignUpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JCheckBox savingAcctCB;
    private javax.swing.JTextField userCity;
    private javax.swing.JTextField userContactNumber;
    private javax.swing.JTextField userDeposit;
    private javax.swing.JTextField userEmailAddress;
    private javax.swing.JTextField userFirstName;
    private javax.swing.JTextField userLastName;
    private javax.swing.JPasswordField userPassword;
    // End of variables declaration//GEN-END:variables
}
